Repository MeetUpEat/Zipbab, pull requests merged in 2024-06, with the labels that each got.

#7 Retrofit + API service + Moshi 설정
  app/build.gradle.kts
  data/build.gradle.kts
  data/src/main/java/com/bestapp/rice/data/model/remote/kakaomap/Address.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/kakaomap/Document.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/kakaomap/Meta.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/kakaomap/RoadAddress.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/kakaomap/SearchLocation.kt
  data/src/main/java/com/bestapp/rice/data/network/AuthInterceptor.kt
  data/src/main/java/com/bestapp/rice/data/network/RetrofitClient.kt
  data/src/main/java/com/bestapp/rice/data/network/SearchLocationService.kt
  data/src/main/java/com/bestapp/rice/data/repository/SearchLocationRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/SearchLocationRepositoryImpl.kt
  gradle/libs.versions.toml
Labels: Feature

#20 앱 설정 Repository 구현
  app/proguard-rules.pro
  app/src/main/java/com/bestapp/rice/App.kt
  build.gradle.kts
  data/build.gradle.kts
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepositoryImpl.kt
  gradle/libs.versions.toml
Labels: Feature

#29 AppRepository 변경된 코드에 따른 설정 화면 코드 수정
  app/build.gradle.kts
  app/src/main/java/com/bestapp/rice/model/FilterUiState.kt
  app/src/main/java/com/bestapp/rice/model/UserUiState.kt
  app/src/main/java/com/bestapp/rice/ui/setting/SettingFragment.kt
  app/src/main/java/com/bestapp/rice/ui/setting/SettingViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/setting/SettingViewModelFactory.kt
  data/build.gradle.kts
  data/src/main/java/com/bestapp/rice/data/model/remote/Filter.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/Meeting.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/PlaceLocation.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/Post.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/Privacy.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/User.kt
  data/src/main/java/com/bestapp/rice/data/network/FirebaseClient.kt
  data/src/main/java/com/bestapp/rice/data/network/RetrofitClient.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/CategoryRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/CategoryRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/SearchLocationRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/StorageRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/StorageRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/tool.kt
  gradle/libs.versions.toml
Labels: Fix

#25 Feat/#22 firestore storage repository 구현
  data/src/main/java/com/bestapp/rice/data/repository/CategoryRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepositoryImpl.kt
Labels: Feature

#12 Feat/#4 홈 화면 UI와 기본 필요한 동작 구현
  app/src/main/java/com/bestapp/rice/model/FilterUiState.kt
  app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
  app/src/main/java/com/bestapp/rice/ui/home/HomeViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/home/HomeViewModelFactory.kt
  app/src/main/java/com/bestapp/rice/ui/home/MoveMyMeetingNavigate.kt
  app/src/main/java/com/bestapp/rice/ui/home/MoveNavigate.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostDiffUtil.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostViewHolder.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/FoodMenuAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/FoodMenuDiffUtil.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/FoodMenuViewHolder.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/MyMeetingAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/MyMeetingDiffUtil.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/MyMeetingViewHolder.kt
  app/src/main/res/drawable/baseline_add_24.xml
  app/src/main/res/drawable/baseline_keyboard_arrow_right_24.xml
  app/src/main/res/drawable/baseline_search_24.xml
  app/src/main/res/drawable/shape_et_round_bg.xml
  app/src/main/res/drawable/shape_item_round_bg.xml
  app/src/main/res/drawable/shape_round_layout_bg.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_cost.xml
  app/src/main/res/layout/item_food_menu.xml
  app/src/main/res/layout/item_my_meet.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature

#10 로그인 및 회원가입 ui + 기능 구현
  app/src/main/java/com/bestapp/rice/ui/MainActivity.kt
  app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
  app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
  app/src/main/java/com/bestapp/rice/ui/signup/SignUpViewModel.kt
  app/src/main/res/drawable/background_button.xml
  app/src/main/res/drawable/background_button_disable.xml
  app/src/main/res/drawable/background_edittext.xml
  app/src/main/res/drawable/background_radius.xml
  app/src/main/res/drawable/baseline_disappear_text.xml
  app/src/main/res/drawable/baseline_edit_calendar_24.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_sign_up.xml
Labels: Design, Feature

#17 Feat/#11 notification fragment & ui
  app/build.gradle.kts
  app/src/main/java/com/bestapp/rice/FireBaseMessageReceiver.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationType.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationViewModel.kt
  app/src/main/res/drawable/icon_notification.xml
  app/src/main/res/drawable/icon_notification_main.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/viewholder_main_notification.xml
  app/src/main/res/layout/viewholder_user_notification.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/bestapp/rice/data/network/RetrofitClient.kt
  data/src/main/java/com/bestapp/rice/data/notification/DownloadToken.kt
  data/src/main/java/com/bestapp/rice/data/notification/NotificationKey.kt
  data/src/main/java/com/bestapp/rice/data/notification/PushMsgJson.kt
  data/src/main/java/com/bestapp/rice/data/notification/RegisterToken.kt
  data/src/main/java/com/bestapp/rice/data/notification/SendMsg.kt
  data/src/main/java/com/bestapp/rice/data/notification/setup/KaKaoService.kt
  data/src/main/java/com/bestapp/rice/data/notification/setup/NoTiInterceptor.kt
Labels: Design, Feature

#33 Revert "Feat/#11 notification fragment & ui"
  app/build.gradle.kts
  app/src/main/java/com/bestapp/rice/FireBaseMessageReceiver.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationType.kt
  app/src/main/java/com/bestapp/rice/ui/notification/NotificationViewModel.kt
  app/src/main/res/drawable/icon_notification.xml
  app/src/main/res/drawable/icon_notification_main.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/viewholder_main_notification.xml
  app/src/main/res/layout/viewholder_user_notification.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/bestapp/rice/data/network/RetrofitClient.kt
  data/src/main/java/com/bestapp/rice/data/notification/DownloadToken.kt
  data/src/main/java/com/bestapp/rice/data/notification/NotificationKey.kt
  data/src/main/java/com/bestapp/rice/data/notification/PushMsgJson.kt
  data/src/main/java/com/bestapp/rice/data/notification/RegisterToken.kt
  data/src/main/java/com/bestapp/rice/data/notification/SendMsg.kt
  data/src/main/java/com/bestapp/rice/data/notification/setup/KaKaoService.kt
  data/src/main/java/com/bestapp/rice/data/notification/setup/NoTiInterceptor.kt
Labels: Fix

#35 Fix/#5 login fragment
  app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
  app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
  app/src/main/res/values/strings.xml
Labels: Fix

#27 프로필 수정 화면 구현
  app/src/main/java/com/bestapp/rice/model/UiStateMapper.kt
  app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/BitmapConverter.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditMessage.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditUiState.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/SubmitUiState.kt
  app/src/main/java/com/bestapp/rice/ui/setting/SettingViewModel.kt
  app/src/main/java/com/bestapp/rice/util/Extension.kt
  app/src/main/res/drawable/baseline_close_24.xml
  app/src/main/res/layout/fragment_profile_edit.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/user_info.xml
Labels: Feature

#24 Feat/#16 recruitment fragment
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestapp/rice/ui/recruitment/ChipType.kt
  app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
  app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentViewModel.kt
  app/src/main/res/color/bg_filter.xml
  app/src/main/res/color/chip_filter.xml
  app/src/main/res/color/text_filter.xml
  app/src/main/res/drawable/background_shape.xml
  app/src/main/res/drawable/baseline_more_time_24.xml
  app/src/main/res/layout/fragment_recruitment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/build.gradle.kts
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepositoryImpl.kt
Labels: Design, Feature

#26 Feat/#13 검색 화면 UI와 기본 필요한 동작 구현
  app/src/main/java/com/bestapp/rice/ui/search/MoveDirection.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchDiffUtil.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchExtension.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchViewHolder.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/img_emptyrice.png
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Feature

#55 Fix/#54 home fragment cost category 안보이는 문제
  app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
  app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostViewHolder.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_cost.xml
Labels: Fix

#40 프로필 이미지 선택 화면, 이미지 권한 처리 구현
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profileimageselect/ProfileImageSelectFragment.kt
  app/src/main/res/layout/item_profile_image_select_gallery.xml
Labels: Feature

#49 fix: User dataclass fix and and server connect
  app/src/main/java/com/bestapp/rice/model/NotificationUiState.kt
  app/src/main/java/com/bestapp/rice/model/UiStateMapper.kt
  app/src/main/java/com/bestapp/rice/model/UserUiState.kt
  app/src/main/java/com/bestapp/rice/model/args/UserActionArg.kt
  app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
  app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
  app/src/main/java/com/bestapp/rice/ui/signup/SignUpViewModel.kt
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/user_info.xml
  data/src/main/java/com/bestapp/rice/data/di/NetworkProviderModule.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/NotificationType.kt
  data/src/main/java/com/bestapp/rice/data/model/remote/User.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepositoryImpl.kt
Labels: Fix

#44 #31 내 모임 보기 페이지 기능 구현
  app/src/main/java/com/bestapp/rice/model/MeetingUiState.kt
  app/src/main/java/com/bestapp/rice/model/UiStateMapper.kt
  app/src/main/java/com/bestapp/rice/model/args/FilterUi.kt
  app/src/main/java/com/bestapp/rice/model/args/ImageUi.kt
  app/src/main/java/com/bestapp/rice/model/args/MeetingUi.kt
  app/src/main/java/com/bestapp/rice/model/args/PlaceLocationUi.kt
  app/src/main/java/com/bestapp/rice/model/args/PostUi.kt
  app/src/main/java/com/bestapp/rice/model/args/ProfileEditUi.kt
  app/src/main/java/com/bestapp/rice/model/args/SelectImageUi.kt
  app/src/main/java/com/bestapp/rice/model/args/UserActionUi.kt
  app/src/main/java/com/bestapp/rice/ui/foodcategory/FoodCategoryViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
  app/src/main/java/com/bestapp/rice/ui/meetingmanagement/MeetingManagementFragment.kt
  app/src/main/java/com/bestapp/rice/ui/mettinglist/MeetingActivationStatus.kt
  app/src/main/java/com/bestapp/rice/ui/mettinglist/MeetingListFragment.kt
  app/src/main/java/com/bestapp/rice/ui/mettinglist/MeetingListUi.kt
  app/src/main/java/com/bestapp/rice/ui/mettinglist/MeetingListUiState.kt
  app/src/main/java/com/bestapp/rice/ui/mettinglist/MeetingListViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/profileimageselect/ProfileImageSelectFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profilepostimageselect/ProfilePostImageSelectFragment.kt
  app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/setting/SettingFragment.kt
  app/src/main/res/drawable/baseline_keyboard_arrow_right_24.xml
  app/src/main/res/drawable/ic_check_disable.xml
  app/src/main/res/drawable/ic_check_enable.xml
  app/src/main/res/drawable/selector_review_activation.xml
  app/src/main/res/drawable/shape_card_view16.xml
  app/src/main/res/drawable/shape_radius_12.xml
  app/src/main/res/drawable/shape_radius_16.xml
  app/src/main/res/drawable/shape_radius_4.xml
  app/src/main/res/drawable/shape_radius_8.xml
  app/src/main/res/layout/fragment_meeting_list.xml
  app/src/main/res/layout/item_my_meeting.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/src/main/java/com/bestapp/rice/data/model/remote/Meeting.kt
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepositoryImpl.kt
Labels: Feature

#53 사용자 documentID 복사 관련 로직 및 UI 구현
  app/src/main/java/com/bestapp/rice/ui/MainActivity.kt
  app/src/main/java/com/bestapp/rice/ui/setting/SettingFragment.kt
  app/src/main/java/com/bestapp/rice/ui/setting/SettingViewModel.kt
  app/src/main/res/drawable/baseline_info_outline_24.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/user_document_id_instruction_view.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/bestapp/rice/data/model/remote/DummyForUrlParsing.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/AppSettingRepositoryImpl.kt
Labels: Feature

#61 Fix/#58 home fragment search fragment 검색바 디자인 수정
  app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
  app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
  app/src/main/res/drawable/shape_back_round_layout_bg.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: Fix

#65 Feat/#50 모임 관리 페이지 UI와 기본 필요한 동작 구현
  app/src/main/java/com/bestapp/rice/ui/meetingmanagement/MeetingManagementFragment.kt
  app/src/main/java/com/bestapp/rice/ui/meetingmanagement/MeetingManagementViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/meetingmanagement/MeetingMemberAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/meetingmanagement/MeetingMemberDiffUtil.kt
  app/src/main/java/com/bestapp/rice/ui/meetingmanagement/MeetingMemberViewHolder.kt
  app/src/main/java/com/bestapp/rice/ui/meetingmanagement/MoveNavigation.kt
  app/src/main/res/color/selector_button_text_color.xml
  app/src/main/res/drawable/selector_button_background.xml
  app/src/main/res/drawable/shape_not_select_round_bg.xml
  app/src/main/res/drawable/shape_not_stroke_round_bg.xml
  app/src/main/res/drawable/shape_select_round_bg.xml
  app/src/main/res/layout/fragment_meeting_management.xml
  app/src/main/res/layout/item_member.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepositoryImpl.kt
Labels: Feature

#62 Feat/#51 비용 카테고리 UI와 기본 필요한 동작 구현
  app/src/main/java/com/bestapp/rice/ui/cost/CostCategoryAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/cost/CostCategoryDiffUtil.kt
  app/src/main/java/com/bestapp/rice/ui/cost/CostCategoryUtil.kt
  app/src/main/java/com/bestapp/rice/ui/cost/CostCategoryViewHolder.kt
  app/src/main/java/com/bestapp/rice/ui/cost/CostCategoryViewpagerAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/cost/CostFragment.kt
  app/src/main/java/com/bestapp/rice/ui/cost/CostViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/cost/InputCostFragment.kt
  app/src/main/java/com/bestapp/rice/ui/cost/MoveMeetingNavi.kt
  app/src/main/res/layout/fragment_cost.xml
  app/src/main/res/layout/fragment_input_cost.xml
  app/src/main/res/layout/item_cost_category.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#64 Feat/#42 모임 신청 페이지 UI와 기본 필요한 동작 구현
  app/src/main/java/com/bestapp/rice/ui/mettinginfo/Event.kt
  app/src/main/java/com/bestapp/rice/ui/mettinginfo/MeetingInfoFragment.kt
  app/src/main/java/com/bestapp/rice/ui/mettinginfo/MeetingInfoViewModel.kt
  app/src/main/res/color/selector_button_text_color.xml
  app/src/main/res/drawable/shape_not_select_round_bg.xml
  app/src/main/res/layout/fragment_meeting_info.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepositoryImpl.kt
Labels: Feature

#69 fix/#68 음식 카테고리의 비로그인 시 모임 참가 신청 페이지로 넘어가게 수정
  app/src/main/java/com/bestapp/rice/ui/foodcategory/FoodCategoryViewModel.kt
Labels: Fix

#72 Fix/#71 homefragment 내 모임 보기 빈 값을 때 처리
  app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: Fix

#66 이미지 포스트 삭제 기능 및 DB 영구 삭제 로직 추가
  app/src/main/java/com/bestapp/rice/ui/profile/DeleteState.kt
  app/src/main/java/com/bestapp/rice/ui/profile/Location.kt
  app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profile/ProfileGalleryAdapter.kt
  app/src/main/java/com/bestapp/rice/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditViewModel.kt
  app/src/main/java/com/bestapp/rice/ui/profileimageselect/ProfileImageSelectFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profilepostimageeditfragment/ProfilePostImageEditFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profilepostimageselect/ProfilePostImageSelectFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_post_image_edit.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/bestapp/rice/data/repository/PostRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/PostRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/StorageRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/StorageRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepositoryImpl.kt
Labels: Feature, Refactor

#77 기본 프로필 로직 수정 및 회원 탈퇴 로직 보강
  app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/rice/ui/profileedit/ProfileEditFragment.kt
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/MeetingRepositoryImpl.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepository.kt
  data/src/main/java/com/bestapp/rice/data/repository/UserRepositoryImpl.kt
Labels: Fix

#86 설정화면에 위치정보 이용약관 탭 추가
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingViewModel.kt
  app/src/main/res/drawable/baseline_my_location_24.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/bestapp/zipbab/data/repository/AppSettingRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/AppSettingRepositoryImpl.kt
Labels: Feature

#88 fix: Map 메모리 누수 제거, 배터리 효율을 고려하여 정확도 감축
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpMapFragment.kt
  app/src/main/java/com/bestapp/zipbab/userlocation/LocationServiceImpl.kt
  app/src/main/res/layout/bottom_sheets_meeting_list.xml
Labels: Fix

#89 사용하지 않는 권한 완전 삭제
  app/src/main/AndroidManifest.xml
Labels: Fix

#90 Refactor/meet up map fragment
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/KakaoMapExtension.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpListAdapter.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpMapFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpMapUi.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpMapViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/mettinglist/MeetingActivationStatus.kt
  app/src/main/java/com/bestapp/zipbab/userlocation/LocationModule.kt
  app/src/main/java/com/bestapp/zipbab/userlocation/LocationService.kt
  app/src/main/java/com/bestapp/zipbab/userlocation/LocationServiceImpl.kt
  app/src/main/java/com/bestapp/zipbab/userlocation/LocationViewModel.kt
  app/src/main/res/values/strings.xml
Labels: Refactor

#92 WorkManager를 이용해서 이미지 업로드 처리
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestapp/zipbab/App.kt
  app/src/main/java/com/bestapp/zipbab/model/PostUiState.kt
  app/src/main/java/com/bestapp/zipbab/model/UiStateMapper.kt
  app/src/main/java/com/bestapp/zipbab/model/UploadState.kt
  app/src/main/java/com/bestapp/zipbab/model/args/ImagePostSubmitUi.kt
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileGalleryAdapter.kt
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileedit/ProfileEditFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/PostImageSelectViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/ProfilePostImageSelectFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/model/SubmitInfo.kt
  app/src/main/res/layout/fragment_profile_post_image_select.xml
  app/src/main/res/layout/item_gallery.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/bestapp/zipbab/data/di/DispatchersModule.kt
  data/src/main/java/com/bestapp/zipbab/data/di/NetworkProviderModule.kt
  data/src/main/java/com/bestapp/zipbab/data/model/UploadStateEntity.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/AppSettingRepositoryImpl.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/UserRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/bestapp/zipbab/data/upload/UploadStateEntityAdapter.kt
  data/src/main/java/com/bestapp/zipbab/data/upload/UploadWorker.kt
  data/src/main/java/com/bestapp/zipbab/data/upload/WorkerUtil.kt
  data/src/main/res/drawable/app_icon.jpg
  data/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: Feature, Refactor

#98 페이징을 이용해서 갤러리 이미지 불러오기
  app/build.gradle.kts
  app/src/main/java/com/bestapp/zipbab/model/UiStateMapper.kt
  app/src/main/java/com/bestapp/zipbab/permission/GalleryImageFetcher.kt
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileedit/ProfileEditFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileimageselect/ProfileImageSelectAdapter.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileimageselect/ProfileImageSelectFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileimageselect/ProfileImageSelectViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/PostGalleryAdapter.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/PostImageSelectViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/ProfilePostImageSelectFragment.kt
  data/build.gradle.kts
  data/src/main/java/com/bestapp/zipbab/data/datasource/GalleryImageFetcher.kt
  data/src/main/java/com/bestapp/zipbab/data/datasource/GalleryPagingSource.kt
  data/src/main/java/com/bestapp/zipbab/data/di/GalleryModule.kt
  data/src/main/java/com/bestapp/zipbab/data/di/ViewModelRepositoryModule.kt
  data/src/main/java/com/bestapp/zipbab/data/model/local/GalleryImageInfo.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/GalleryRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/GalleryRepositoryImpl.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/MeetingRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/StorageRepositoryImpl.kt
  gradle/libs.versions.toml
Labels: Feature, Refactor

#108 #107 DarkMode 지원을 위해 내 모임 Item에 Selector 적용
  app/src/main/res/layout/item_my_meeting.xml
Labels: Design

#109 Feat/#87 fcm notification fragment
  app/build.gradle.kts
  app/src/main/java/com/bestapp/zipbab/ui/home/HomeFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/home/HomeViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/mettinginfo/MeetingInfoFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/mettinginfo/MeetingInfoViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/notification/NotificationAdapter.kt
  app/src/main/java/com/bestapp/zipbab/ui/notification/NotificationFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/notification/NotificationType.kt
  app/src/main/java/com/bestapp/zipbab/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/recruitment/RecruitmentFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/signup/SignUpFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/signup/SignUpViewModel.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/layout/viewholder_main_notification.xml
  app/src/main/res/layout/viewholder_user_notification.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/bestapp/zipbab/data/FirestoreDB/FirestoreDB.kt
  data/src/main/java/com/bestapp/zipbab/data/di/NetworkProviderModule.kt
  data/src/main/java/com/bestapp/zipbab/data/di/ViewModelRepositoryModule.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/NotificationTypeResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/PlaceLocation.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/UserResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/access/Access.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/access/AccessReturn.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/fcm/AccessToken.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/fcm/Message.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/fcm/NotificationData.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/fcm/PushNotification.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/preference/SharedPreference.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/refresh/Refresh.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/refresh/RefreshReturn.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/setup/GooGleRefreshService.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/setup/GooGleService.kt
  data/src/main/java/com/bestapp/zipbab/data/notification/setup/KaKaoService.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/NotificationRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/ProviderRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/ProviderRepositoryImpl.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/UserRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/UserRepositoryImpl.kt
Labels: Feature

#99 #97 migration, 카카오 to 네이버 지도
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bestapp/zipbab/App.kt
  app/src/main/java/com/bestapp/zipbab/model/kakaoLocation/AddressUiState.kt
  app/src/main/java/com/bestapp/zipbab/model/kakaoLocation/DocumentUiState.kt
  app/src/main/java/com/bestapp/zipbab/model/kakaoLocation/MetaUiState.kt
  app/src/main/java/com/bestapp/zipbab/model/kakaoLocation/RoadAddressUiState.kt
  app/src/main/java/com/bestapp/zipbab/model/kakaoLocation/SearchLocationUiState.kt
  app/src/main/java/com/bestapp/zipbab/permission/LocationPermissionManager.kt
  app/src/main/java/com/bestapp/zipbab/permission/LocationPermissionSnackBar.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/KakaoMapExtension.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpListAdapter.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpMapFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/MeetUpMapViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/NaverMapExtension.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/model/MeetUpMapUi.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/model/MeetUpMapUiState.kt
  app/src/main/java/com/bestapp/zipbab/ui/meetupmap/model/MeetingMarkerUiStates.kt
  app/src/main/java/com/bestapp/zipbab/ui/mettinglist/MeetingListFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/mettinglist/MeetingListUi.kt
  app/src/main/java/com/bestapp/zipbab/ui/notification/NotificationFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/recruitment/RecruitmentFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/recruitment/RecruitmentViewModel.kt
  app/src/main/res/animator/nav_default_enter_anim.xml
  app/src/main/res/animator/nav_default_exit_anim.xml
  app/src/main/res/animator/nav_default_pop_enter_anim.xml
  app/src/main/res/animator/nav_default_pop_exit_anim.xml
  app/src/main/res/drawable/multiple_image.xml
  app/src/main/res/layout/bottom_sheets_meeting_list.xml
  app/src/main/res/layout/fragment_meet_up_map.xml
  app/src/main/res/layout/item_meet_up_list.xml
  app/src/main/res/layout/item_setting_fragment.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/text_styles.xml
  data/src/main/java/com/bestapp/zipbab/data/model/remote/kakaomap/AddressResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/kakaomap/DocumentResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/kakaomap/MetaResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/kakaomap/RoadAddressResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/kakaomap/SearchLocationResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/CategoryRepositoryImpl.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Design, Feature, Fix, Refactor

#111 코드 개선 및 버그 수정
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileedit/ProfileEditFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileedit/ProfileEditViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileimageselect/ProfileImageSelectFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/PostImageSelectViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/profilepostimageselect/ProfilePostImageSelectFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_profile.xml
Labels: Feature, Fix, Refactor

#115 Hot fix
  app/build.gradle.kts
  app/src/main/java/com/bestapp/zipbab/ui/profileimageselect/ProfileImageSelectFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/LoadingState.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: Fix
