Repository MeetUpEat/Zipbab, pull requests merged in 2024-07, with the labels that each got.

#119 Feat/#113 feed back fragment
  app/src/main/java/com/bestapp/zipbab/ui/mettinginfo/MeetingInfoFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/mettinginfo/MeetingInfoViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/notification/NotificationFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/recruitment/RecruitmentFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/signup/SignUpFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/signup/SignUpViewModel.kt
  app/src/main/res/drawable/background_button_disable.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_meeting_info.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/layout/viewholder_user_notification.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#122 fix: call back 방식으로 변환
  app/src/main/java/com/bestapp/zipbab/ui/signup/SignUpFragment.kt
Labels: Fix

#120 버그 수정 및 코드 개선
  app/src/main/java/com/bestapp/zipbab/model/SignOutState.kt
  app/src/main/java/com/bestapp/zipbab/model/UiStateMapper.kt
  app/src/main/java/com/bestapp/zipbab/ui/profileimageselect/ProfileImageSelectFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingMessage.kt
  app/src/main/java/com/bestapp/zipbab/ui/setting/SettingViewModel.kt
  app/src/main/java/com/bestapp/zipbab/ui/term/TermFragment.kt
  app/src/main/res/drawable/instruction_background.xml
  app/src/main/res/drawable/triangle.xml
  app/src/main/res/drawable/upper_triangle.xml
  app/src/main/res/layout/fragment_term.xml
  app/src/main/res/layout/temperature_instruction_view.xml
  app/src/main/res/layout/user_document_id_instruction_view.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/bestapp/zipbab/data/FirestoreDB/FirestoreDB.kt
  data/src/main/java/com/bestapp/zipbab/data/model/local/SignOutEntity.kt
  data/src/main/java/com/bestapp/zipbab/data/model/remote/SignOutForbiddenResponse.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/UserRepository.kt
  data/src/main/java/com/bestapp/zipbab/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/bestapp/zipbab/data/upload/UploadWorker.kt
Labels: Fix, Refactor

#124 Item Decoration 문제 해결 및 Version 1.0.6으로 수정
  app/build.gradle.kts
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileFragment.kt
  app/src/main/java/com/bestapp/zipbab/ui/profile/ProfileViewModel.kt
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/key.xml
Labels: Fix
